USE [QUANLYMYPHAM]
GO

/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 03-Nov-22 10:49:03 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KHACHHANG](
	[MAKH] [char](4) NOT NULL,
	[HOTEN] [nvarchar](80) NULL,
	[DIACHI] [nvarchar](100) NULL,
	[SDT] [nvarchar](10) NULL,
	[NGSINH] [date] NULL,
	[DOANHSO] [money] NULL,
	[NGDK] [date] NULL,
	[MACN] [char](4) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
 CONSTRAINT [PK__KHACHHAN__603F592C46935237] PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[KHACHHANG] ADD  CONSTRAINT [MSmerge_df_rowguid_78FF8F99D22845CE86457EB9F16ED721]  DEFAULT (newsequentialid()) FOR [rowguid]
GO

