USE [QUANLYMYPHAM]
GO

/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 03-Nov-22 10:48:46 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [char](4) NOT NULL,
	[HOTEN] [nvarchar](40) NULL,
	[GIOITINH] [nvarchar](4) NULL,
	[NGVL] [date] NULL,
	[CHUCVU] [nvarchar](30) NULL,
	[MACN] [char](4) NULL,
	[SDT] [nvarchar](10) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
 CONSTRAINT [PK__NHANVIEN__603F5114162FD7DB] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[NHANVIEN] ADD  CONSTRAINT [MSmerge_df_rowguid_85D078BBA160486C8D967BE02949C6DC]  DEFAULT (newsequentialid()) FOR [rowguid]
GO

